# **what?**
# - create a `changie` entry for automated PRs using this template:
#
#     kind: <per action matrix> (e.g. Dependencies)
#     body: <PR title>
#     time: <current timestamp>
#     custom:
#       Author: <PR User Login (generally the bot)>
#       PR: <PR number>
#
# **why?**
# - automate and standardize `changie` entry generation for automated PRs
#
# **when?**
# - a PR is created with the appropriate label
# - the appropriate label is added to an open PR
#
# **how to add another bot?**
# - add the label and changie kind to the include matrix
name: "Bot changelog"

on:
    pull_request:
        types:
        -   opened
        -   labeled

permissions:
    contents: write
    pull-requests: read

jobs:
    generate_changelog:
        strategy:
            matrix:
                include:
                -   label: "dependencies"
                    changie-kind: "Dependencies"
        runs-on: ubuntu-latest
        steps:
        -   name: "Create and commit a changie entry for an automated PR"
            if: ${{ contains(github.event.pull_request.labels.*.name, matrix.label) }}
            uses: emmyoop/changie_bot@v1
            with:
                GITHUB_TOKEN: ${{ secrets.FISHTOWN_BOT_PAT }}
                commit_author_name: "Github Build Bot"
                commit_author_email: "<buildbot@fishtownanalytics.com>"
                commit_message: "[automated] changie entry"
                changie_kind: ${{ matrix.changie-kind }}
                label: ${{ matrix.label }}
                custom_changelog_string: "custom:\n  Author: ${{ github.event.pull_request.user.login }}\n  PR: ${{ github.event.pull_request.number }}"
