# **what?**
# Cleanup branches left over from automation and testing.
# Also cleanup draft releases from release testing.
#
# **why?**
# The automations are leaving behind branches and releases that clutter the repository.
# Sometimes we need them to debug processes so we don't want them immediately deleted.
# Running on Saturday to avoid running at the same time as an actual release
# to prevent breaking a release mid-release.
#
# **when?**
# - every Saturday at noon UTC
# - manually
name: "Clean repo"

on:
    schedule:
    -   cron: '0 12 * * SAT'  # noon UTC on Saturday - details in `why` above
    workflow_dispatch:

permissions:
    contents: write

jobs:
    cleanup-repo:
        uses: dbt-labs/actions/.github/workflows/repository-cleanup.yml@main
        secrets: inherit
