# **what?**
# Run code quality checks, e.g. `black`, `flake8`, `mypy`, via `pre-commit`
#
# **why?**
# Ensure code quality meets dbt Labs standards
#
# **when?**
# - runs on all PRs into protected branches
# - runs indirectly during releases and release tests
# - can be manually run
name: "Code quality"

on:
    pull_request:
    push:
        branches:
        -   "main"
        -   "*.latest"
    workflow_call:
        inputs:
            branch:
                description: "The branch/tag to run code quality on"
                type: string
                default: "main"
            dbt-adapters-branch:
                description: "The branch/tag of `dbt-adapters` to use"
                type: string
                default: "main"
            dbt-common-branch:
                description: "The branch/tag of `dbt-common` to use"
                type: string
                default: "main"
    workflow_dispatch:
        inputs:
            branch:
                description: "The branch/tag to run code quality on"
                type: string
                default: "main"
            dbt-adapters-branch:
                description: "The branch/tag of `dbt-adapters` to use"
                type: string
                default: "main"
            dbt-common-branch:
                description: "The branch/tag of `dbt-common` to use"
                type: string
                default: "main"

permissions: read-all

concurrency:
    group: "${{ github.workflow }}-${{ github.event_name }}-${{ contains(github.event_name, 'pull_request') && github.event.pull_request.head.ref || github.sha }}"
    cancel-in-progress: true

jobs:
    code-quality:
        name: "Code quality"
        runs-on: ubuntu-latest
        steps:
        -   name: "Check out ${{ github.repository }}@${{ inputs.branch }} (non-PR)"
            if: github.event_name != 'pull_request_target'
            uses: actions/checkout@v4
            with:
                ref: ${{ inputs.branch }}
                persist-credentials: false

        -   name: "Check out ${{ github.repository }}@${{ inputs.branch }} (PR)"
            if: github.event_name == 'pull_request_target'
            uses: actions/checkout@v4
            with:
                ref: ${{ github.event.pull_request.head.sha }}

        -   name: "Setup environment"
            uses: dbt-labs/dbt-adapters/.github/actions/setup-environment@update-workflows
            with:
                python-version: ${{ vars.DBT_TEST_PYTHON_VERSION }}

        -   name: "Update development branches"
            if: ${{ contains(github.event_name, 'workflow_') }}
            uses: ./.github/actions/update-dev-branches
            with:
                dbt-adapters-branch: ${{ inputs.dbt-adapters-branch }}
                dbt-common-branch: ${{ inputs.dbt-common-branch }}

        -   name: "Run code quality"
            shell: bash
            run: hatch run code-quality
