# **what?**
# - create a new branch from `main` (generally `*.latest`)
# - clean up files in `.changes/unreleased` and `.changes/<version> on `main`
# - bump `main` to the input version
#
# **why?**
# - automate and standardize workflow
# - reduce the workload of engineers for routine actions
# - reduce change for human error
#
# **when?**
# - manually
name: "Cut release branch"

on:
    workflow_dispatch:
        inputs:
            next-version:
                description: "The alpha version main should bump to (e.g. 1.6.0a1)"
                type: string
                required: true
            release-branch:
                description: "The full name of the new branch (e.g. 1.5.latest)"
                type: string
                required: true

permissions:
    contents: write

jobs:
    cut-release-branch:
        name: "Create ${{ inputs.release-branch }} and clean up `main`"
        uses: dbt-labs/actions/.github/workflows/cut-release-branch.yml@main
        with:
            version_to_bump_main: ${{ inputs.next-version }}
            new_branch_name: ${{ inputs.release-branch }}
            PR_title: "Prepare `main` for `${{ inputs.next-version }}`"
            PR_body: "Cleanup `main` after cutting new `${{ inputs.release-branch }}` release branch"
        secrets:
            FISHTOWN_BOT_PAT: ${{ secrets.FISHTOWN_BOT_PAT }}
