name: "Integration tests"

on:
    workflow_call:
        inputs:
            ref:
                description: "The branch/tag/commit to run integration tests on"
                type: string
                required: true
            dbt-adapters-branch:
                description: "The branch/tag of `dbt-adapters` to use"
                type: string
                default: ""
            dbt-common-branch:
                description: "The branch/tag of `dbt-common` to use"
                type: string
                default: ""
            dbt-core-branch:
                description: "The branch/tag of `dbt-core` to use"
                type: string
                default: ""
    workflow_dispatch:
        inputs:
            branch:
                description: "The branch/tag to run integration tests on"
                type: string
                default: "main"
            dbt-adapters-branch:
                description: "The branch/tag of `dbt-adapters` to use"
                type: string
                default: ""
            dbt-common-branch:
                description: "The branch/tag of `dbt-common` to use"
                type: string
                default: ""
            dbt-core-branch:
                description: "The branch/tag of `dbt-core` to use"
                type: string
                default: ""

permissions: read-all

concurrency:
    group: "${{ github.workflow }}-${{ github.event_name }}-${{ inputs.ref }}"
    cancel-in-progress: true

jobs:
    require-approval-on-forks:
        # if it's a pull request from a fork that has not been approved yet, don't run tests
        if: >-
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository &&
            !contains(github.event.pull_request.labels.*.name, 'ok to test')
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
        -   name: "Author requires permission to run tests"
            uses: unsplash/comment-on-pr@master
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
                msg: |
                    "Thanks for your contribution! "\
                    "This PR was created from a fork, integration tests need to be approved prior to running. "\
                    "@dbt-labs/core will review this PR and approve running integration tests."
                check_for_duplicate_msg: true

        -   name: "Exit"
            shell: bash
            run: exit 0

    integration-tests:
        name: "Integration tests"
        needs: require-approval-on-forks
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ${{ fromJSON(vars.DBT_PYTHON_VERSIONS) }}
                include:
                -   os: macos-latest
                    python-version: ${{ fromJSON(vars.DBT_PYTHON_VERSION) }}
                -   os: windows-latest
                    python-version: ${{ fromJSON(vars.DBT_PYTHON_VERSION) }}
        steps:
        -   name: "Check out ${{ github.repository }}@${{ inputs.ref }}"
            uses: actions/checkout@v4
            with:
                ref: ${{ inputs.ref }}
                persist-credentials: false

        -   name: "Setup environment"
            uses: dbt-labs/actions/hatch/environment/create@add-hatch-actions
            with:
                python-version: ${{ matrix.python-version }}

        -   name: "Update development branches"
            uses: ./.github/actions/update-dev-branches
            with:
                dbt-adapters-branch: ${{ inputs.dbt-adapters-branch }}
                dbt-common-branch: ${{ inputs.dbt-common-branch }}
                dbt-core-branch: ${{ inputs.dbt-core-branch }}

        -   name: "Create AWS IAM profile"
            run: |
                aws configure set aws_access_key_id $REDSHIFT_TEST_ACCESS_KEY_ID
                aws configure set aws_secret_access_key $REDSHIFT_TEST_SECRET_ACCESS_KEY
                aws configure set region $REDSHIFT_TEST_REGION
                aws configure set output json

        -   name: "Run integration tests"
            shell: bash
            run: hatch run integration-tests:all
            env:
                REDSHIFT_TEST_HOST: ${{ secrets.REDSHIFT_TEST_HOST }}
                REDSHIFT_TEST_PORT: ${{ vars.REDSHIFT_TEST_PORT }}
                REDSHIFT_TEST_DBNAME: ${{ vars.REDSHIFT_TEST_DBNAME }}
                REDSHIFT_TEST_USER: ${{ vars.REDSHIFT_TEST_USER }}
                REDSHIFT_TEST_PASS: ${{ secrets.REDSHIFT_TEST_PASS }}
                REDSHIFT_TEST_CLUSTER_ID: ${{ vars.REDSHIFT_TEST_CLUSTER_ID }}
                REDSHIFT_TEST_IAM_PROFILE: ${{ vars.REDSHIFT_TEST_IAM_PROFILE }}
                REDSHIFT_TEST_ACCESS_KEY_ID: ${{ vars.REDSHIFT_TEST_ACCESS_KEY_ID }}
                REDSHIFT_TEST_SECRET_ACCESS_KEY: ${{ secrets.REDSHIFT_TEST_SECRET_ACCESS_KEY }}
                REDSHIFT_TEST_REGION: ${{ vars.REDSHIFT_TEST_REGION }}
                DBT_TEST_USER_1: ${{ vars.REDSHIFT_TEST_USER_1 }}
                DBT_TEST_USER_2: ${{ vars.REDSHIFT_TEST_USER_2 }}
                DBT_TEST_USER_3: ${{ vars.REDSHIFT_TEST_USER_3 }}
                DBT_INVOCATION_ENV: ${{ vars.DBT_INVOCATION_ENV }}
                DD_CIVISIBILITY_AGENTLESS_ENABLED: true
                DD_API_KEY: ${{ secrets.DATADOG_API_KEY }}
                DD_SITE: ${{ vars.DD_SITE }}
                DD_ENV: ${{ vars.DD_ENV }}
                DD_SERVICE: ${{ github.event.repository.name }}

    aggregate-results:
        name: "Collect integration tests results"
        needs: integration-tests
        if: always() && !cancelled()
        runs-on: ubuntu-latest
        steps:
        -   name: "[INFO] Integration tests - FAILED"
            if: failure()
            shell: bash
            run: echo "::notice title=$TITLE::$MESSAGE" && exit 1
            env:
                TITLE: "Integration tests - FAILED"
                MESSAGE: "Integration tests failed!"

        -   name: "[INFO] Integration tests - PASSED"
            if: ${{ !failure() }}  # includes skipped
            shell: bash
            run: echo "::notice title=$TITLE::$MESSAGE"
            env:
                TITLE: "Integration tests - PASSED"
                MESSAGE: "Integration tests completed successfully!"
