# **what?**
# - removes `awaiting_response` label
# - adds 'triage` label
#
# **why?**
# - automates triaging of issues that needs our attention due to comments
#
# **when?**
# - someone comments on an issue with the `awaiting_response` label
name: "Update triage label"

on: issue_comment

permissions:
    issues: write

jobs:
    triage-label:
        if: contains(github.event.issue.labels.*.name, 'awaiting_response')
        uses: dbt-labs/actions/.github/workflows/swap-labels.yml@main
        with:
            add_label: "triage"
            remove_label: "awaiting_response"
        secrets: inherit
