# **what?**
# - verifies the PR contains a file committed under the `/.changes` directory
#
# **why?**
# - ensure code changes are reflected in the CHANGELOG
#
# **when?**
# - a PR against a protected branch is opened or reopened
# - labels are updated on a PR against a protected branch
# - new code is pushed to a PR against a protected branch
#
# The action will get skipped if the 'Skip Changelog' label is present.
name: "Changie check"

on:
    pull_request:
        types:
        -   opened
        -   reopened
        -   labeled
        -   unlabeled
        -   synchronize

defaults:
    run:
        shell: bash

permissions:
    contents: read
    pull-requests: write

jobs:
    changelog:
        uses: dbt-labs/actions/.github/workflows/changelog-existence.yml@main
        with:
            changelog_comment: "Thank you for your pull request! We could not find a changelog entry for this change. For details on how to document a change, see the [dbt-redshift contributing guide](https://github.com/dbt-labs/dbt-redshift/blob/main/CONTRIBUTING.md)."
            skip_label: "Skip Changelog"
        secrets: inherit
