# **what?**
# Release workflow provides the following steps:
# - checkout the given commit;
# - validate version in sources and changelog file for given version;
# - bump the version and generate a changelog if needed;
# - merge all changes to the target branch if needed;
# - run unit and integration tests against given commit;
# - build and package that SHA;
# - release it to GitHub and PyPI with that specific build;
#
# **why?**
# Ensure an automated and tested release process
#
# **when?**
# This workflow can be run manually on demand or can be called by other workflows
name: "Release pipeline"
run-name: "Release `${{ inputs.version }}` to `${{ inputs.deploy-environment }}`"

on:
    workflow_call:
        inputs:
            sha:
                description: "The commit sha to release"
                type: string
                required: true
            branch:
                description: "The branch to release from"
                type: string
                default: "main"
            version:
                description: "The release version (e.g. 1.0.0b1)"
                type: string
                required: true
            deploy-environment:
                description: "Where to publish"
                type: string
                default: "prod"
            publish-slack-override:
                description: "Use to publish a Slack notification for non-prod deploy environments"
                type: boolean
                default: false
    workflow_dispatch:
        inputs:
            sha:
                description: "The commit sha to release"
                type: string
                required: true
            branch:
                description: "The branch to release from"
                type: string
                default: "main"
            version:
                description: "The release version (e.g. 1.0.0b1)"
                type: string
                required: true
            deploy-environment:
                description: "Where to publish"
                type: environment
            publish-slack-override:
                description: "Use to publish a Slack notification for non-prod deploy environments"
                type: boolean
                default: false

# this is the permission that allows creating a new release to both GitHub and PyPI
permissions:
    contents: write
    id-token: write

# deploying the same version of a package to the same environment should override any previous deployment with those attributes
concurrency:
    group: "${{ github.workflow }}-${{ inputs.version }}-${{ inputs.deploy-environment }}"
    cancel-in-progress: true

jobs:
    release-inputs:
        name: "Release inputs"
        runs-on: ubuntu-latest
        outputs:
            archive-name: ${{ steps.computed-inputs.outputs.archive-name }}
        steps:
        -   name: "Set: archive name"
            id: archive
            shell: bash
            run: |
              archive_name=${{ inputs.package }}-${{ inputs.version_number }}-${{ inputs.deploy-environment }}
              echo "name=$archive_name" >> $GITHUB_OUTPUT

        -   name: "[DEBUG] Inputs"
            shell: bash
            run: |
                echo branch              : ${{ inputs.branch }}
                echo package             : ${{ inputs.package }}
                echo version             : ${{ inputs.version }}
                echo deploy-environment  : ${{ inputs.deploy-environment }}
                echo archive-name        : ${{ steps.archive.outputs.name }}
                echo dbt-adapters-branch : ${{ inputs.dbt-adapters-branch }}
                echo dbt-common-branch   : ${{ inputs.dbt-common-branch }}
                echo dbt-core-branch     : ${{ inputs.dbt-core-branch }}

    release-branch:
        name: "Create a release branch"
        needs: release-inputs
        uses: dbt-labs/dbt-adapters/.github/workflows/release-branch-create.yml@update-workflows
        with:
            branch: ${{ inputs.branch }}
            version: ${{ inputs.version }}
        secrets: inherit

    version-bump:
        name: "Bump the version"
        runs-on: ubuntu-latest
        needs: release-branch
        steps:
        -   name: "Check out ${{ github.event.repository.name }}@${{ inputs.branch }}"
            uses: actions/checkout@v4
            with:
                ref: ${{ needs.release-branch.outputs.branch }}

        -   name: "Bump version to `${{ inputs.version }}`"
            shell: bash
            run: hatch version ${{ inputs.version }}

        -   name: "Commit and push changes"
            shell: bash
            run: commit

    changelog:
        name: "Generate a new changelog"
        needs: release-branch
        uses: dbt-labs/dbt-adapters/.github/workflows/build-changelog.yml@update-workflows
        with:
            branch: ${{ needs.release-branch.outputs.branch }}
            version: ${{ inputs.version }}
        secrets: inherit

    code-quality:
        name: "Run code quality"
        needs:
        -   release-branch
        -   version-bump
        -   changelog
        uses: ./.github/workflows/code-quality.yml
        with:
            branch: ${{ needs.release-branch.outputs.branch }}

    unit-tests:
        name: "Run unit tests"
        needs:
        -   release-branch
        -   version-bump
        -   changelog
        uses: ./.github/workflows/unit-tests.yml
        with:
            branch: ${{ needs.release-branch.outputs.branch }}

    integration-tests:
        name: "Run unit tests"
        needs:
        -   release-branch
        -   version-bump
        -   changelog
        uses: ./.github/workflows/integration-tests.yml
        with:
            branch: ${{ needs.release-branch.outputs.branch }}

    build-artifacts:
        name: "Build artifacts"
        if: ${{ !failure() && !cancelled() }}
        needs:
        -   release-inputs
        -   release-branch
        -   code-quality
        -   unit-tests
        -   integration-tests
        uses: ./.github/workflows/build-artifacts.yml
        with:
            branch: ${{ needs.release-branch.outputs.branch }}
            archive-name: ${{ needs.release-inputs.outputs.archive-name }}

    merge-changes:
        name: "Merge the version bump and changelog updates"
        needs:
        -   build-artifacts
        -   release-branch
        if: >-
            !failure() && !cancelled() &&
            inputs.deploy-environment == 'prod' &&
            needs.release-branch.outputs.name
        uses: dbt-labs/dbt-adapters/.github/workflows/release-branch-merge.yml@update-workflows
        with:
            branch: ${{ inputs.branch }}
            release-branch: ${{ needs.release-branch.outputs.branch }}
        secrets: inherit

    publish-github:
        name: "Publish to GitHub"
        if: ${{ !failure() && !cancelled() }}
        needs:
        -   release-inputs
        -   changelog
        -   merge-changes
        uses: dbt-labs/dbt-adapters/.github/workflows/publish-github.yml@update-workflows
        with:
            archive-name: ${{ needs.release-inputs.outputs.archive-name }}
            version: ${{ inputs.version }}
            deploy-environment: ${{ inputs.deploy-environment }}
            sha: ${{ needs.merge-changes.outputs.sha }}
            changelog-path: ${{ needs.changelog.outputs.changelog-path }}

    publish-pypi:
        name: "Publish to PyPI"
        if: ${{ !failure() && !cancelled() }}
        needs:
        -   release-inputs
        -   merge-changes
        uses: dbt-labs/dbt-adapters/.github/workflows/publish-pypi.yml@update-workflows
        with:
            archive-name: ${{ needs.release-inputs.outputs.archive-name }}
            version: ${{ inputs.version }}
            deploy-environment: ${{ inputs.deploy-environment }}

    publish-pypi-internal:
        name: "Publish to internal PyPI"
        if: ${{ !failure() && !cancelled() }}
        needs:
        -   release-inputs
        -   merge-changes
        uses: dbt-labs/dbt-release/.github/workflows/internal-archive-release.yml@main
        with:
            version_number: "${{ inputs.version }}"
            package_test_command: "python -c \"import dbt.adapters.redshift\""
            dbms_name: "redshift"
            ref: ${{ needs.merge-changes.outputs.sha }}
        secrets: inherit

    slack-notification:
        name: "Slack notification"
        if: ${{ failure() && (inputs.deploy-environment == 'prod' || inputs.publish-slack-override) }}
        needs:
        -   github-release
        -   pypi-release
        uses: dbt-labs/dbt-release/.github/workflows/slack-post-notification.yml@main
        with:
            status: "failure"
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEV_ADAPTER_ALERTS }}
