# **what?**
# - delete branches left over from automation and testing
# - remove draft releases from release testing
#
# **why?**
# - remove clutter from the repository
# - allow automated processes to leave artifacts for debugging and troubleshooting
#
# **when?**
# - every Saturday at noon UTC
# - manually
#
# Runs on Saturday to avoid running at the same time as production release and breaking the release.
name: "Repo maintenance"

on:
    schedule:
    -   cron: '0 12 * * SAT'  # noon UTC on Saturday
    workflow_dispatch:

permissions:
    contents: write

jobs:
    repository-cleanup:
        uses: dbt-labs/actions/.github/workflows/repository-cleanup.yml@main
        secrets: inherit
