# **what?**
# When the core team triages, we sometimes need more information from the issue creator.  In
# those cases we remove the `triage` label and add the `awaiting_response` label.  Once we
# recieve a response in the form of a comment, we want the `awaiting_response` label removed
# in favor of the `triage` label so we are aware that the issue needs action.
#
# **why?**
# To help with out team triage issue tracking
#
# **when?**
# This will run when a comment is added to an issue and that issue has to `awaiting_response` label.
name: "Update triage Label"

on: issue_comment

permissions:
    issues: write

jobs:
    triage-label:
        if: contains(github.event.issue.labels.*.name, 'awaiting_response')
        uses: dbt-labs/actions/.github/workflows/swap-labels.yml@main
        with:
            add_label: "triage"
            remove_label: "awaiting_response"
        # this is only acceptable because we own the action we're calling
        secrets: inherit
