# **what?**
# - delete branches left over from automation and testing
# - remove draft releases from release testing
# - mark old PRs and issues as stale
# - close PRs and issues marked stale
#
# **why?**
# - remove clutter from the repository
# - allow automated processes to leave artifacts for debugging and troubleshooting
#
# **when?**
# - weekly base on DBT_WEEKLY_MAINTENANCE_SCHEDULE
# - manually
#
# Runs on Saturday to avoid running at the same time as production release and breaking the release.
name: "Weekly maintenance"

on:
    schedule:
    -   cron: ${{ vars.DBT_WEEKLY_MAINTENANCE_SCHEDULE }}
    workflow_dispatch:

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    repository-cleanup:
        uses: dbt-labs/actions/.github/workflows/repository-cleanup.yml@main
        secrets: inherit

    stale-issues:
        uses: dbt-labs/actions/.github/workflows/stale-bot-matrix.yml@main
